In [1]:
import pandas as pd 
from sklearn import preprocessing

In [36]:
data=pd.read_csv(r"C:\Users\Welcome\Music\ass3\Book2.csv")
data

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Gender,Age,Placement_Offer_Count
0,72,85,75,90,2020,1,35,2
1,65,80,70,85,2019,0,42,1
2,78,90,72,88,2021,1,60,3
3,68,82,76,92,2018,0,55,1
4,75,88,78,95,2020,1,63,2
5,60,77,64,80,2019,0,45,1
6,70,83,79,89,2021,1,38,3
7,74,86,72,93,2020,0,50,2
8,61,76,68,78,2018,1,72,1
9,80,92,75,97,2021,0,61,3
10,64,79,65,82,2019,1,36,1
11,77,89,73,91,2020,0,49,2
12,70,84,69,85,2021,1,68,1
13,66,81,72,88,2019,0,57,2
14,73,87,78,94,2020,1,40,3
15,79,90,77,98,2021,0,54,3
16,63,78,70,81,2020,1,44,1
17,72,84,71,86,2021,0,51,2
18,68,79,64,79,2019,1,48,1
19,76,91,76,93,2020,0,33,3
20,65,80,73,87,2021,1,70,2
21,71,85,77,92,2020,0,59,1
22,60,75,68,79,2021,1,44,1
23,78,88,79,95,2020,0,39,3
24,67,82,72,84,2019,1,50,2
25,74,86,70,90,2021,0,53,1
26,79,89,75,92,2020,1,64,2
27,62,77,64,81,2019,0,66,1
28,75,88,78,95,2021,1,60,3
29,64,81,70,83,2020,0,47,1
30,76,90,75,94,2021,1,58,2

In [38]:
# Calculate mean, median, and mode 
mean_values = data.mean()
median_values = data.median()
mode_values = data.mode().iloc[0]

In [39]:
print("Mean Values:\n", mean_values)
print("\nMedian Values:\n", median_values)
print("\nMode Values:\n", mode_values)

Mean Values:
 Math_Score                 70.387097
Reading_Score              83.935484
Writing_Score              72.419355
Placement_Score            88.258065
Club_Join_Date           2020.000000
Gender                      0.516129
Age                        51.967742
Placement_Offer_Count       1.838710
dtype: float64

Median Values:
 Math_Score                 71.0
Reading_Score              84.0
Writing_Score              72.0
Placement_Score            89.0
Club_Join_Date           2020.0
Gender                      1.0
Age                        51.0
Placement_Offer_Count       2.0
dtype: float64

Mode Values:
 Math_Score                 60.0
Reading_Score              88.0
Writing_Score              70.0
Placement_Score            92.0
Club_Join_Date           2020.0
Gender                      1.0
Age                        44.0
Placement_Offer_Count       1.0
Name: 0, dtype: float64

In [40]:
grouped_age_mean = data.groupby(['Gender'])['Placement_Score'].mean()
print("\nGrouped Age Mean:\n", grouped_age_mean)

Grouped Age Mean:
 Gender
0    89.6
1    87.0
Name: Placement_Score, dtype: float64

In [42]:
# Encoding categorical variable (Gender)
enc = preprocessing.OneHotEncoder()
enc_data = pd.DataFrame(enc.fit_transform(data[['Gender']]).toarray())

In [45]:
# Concatenate encoded values to DataFrame
data_encode = data.join(enc_data)
print("\nEncoded DataFrame:\n", data_encode)

Encoded DataFrame:
     Math_Score  Reading_Score  Writing_Score  Placement_Score  Club_Join_Date  \
0           72             85             75               90            2020
1           65             80             70               85            2019
2           78             90             72               88            2021
3           68             82             76               92            2018
4           75             88             78               95            2020
5           60             77             64               80            2019
6           70             83             79               89            2021
7           74             86             72               93            2020
8           61             76             68               78            2018
9           80             92             75               97            2021
10          64             79             65               82            2019
11          77             89             73               91            2020
12          70             84             69               85            2021
13          66             81             72               88            2019
14          73             87             78               94            2020
15          79             90             77               98            2021
16          63             78             70               81            2020
17          72             84             71               86            2021
18          68             79             64               79            2019
19          76             91             76               93            2020
20          65             80             73               87            2021
21          71             85             77               92            2020
22          60             75             68               79            2021
23          78             88             79               95            2020
24          67             82             72               84            2019
25          74             86             70               90            2021
26          79             89             75               92            2020
27          62             77             64               81            2019
28          75             88             78               95            2021
29          64             81             70               83            2020
30          76             90             75               94            2021

    Gender  Age  Placement_Offer_Count    0    1
0        1   35                      2  0.0  1.0
1        0   42                      1  1.0  0.0
2        1   60                      3  0.0  1.0
3        0   55                      1  1.0  0.0
4        1   63                      2  0.0  1.0
5        0   45                      1  1.0  0.0
6        1   38                      3  0.0  1.0
7        0   50                      2  1.0  0.0
8        1   72                      1  0.0  1.0
9        0   61                      3  1.0  0.0
10       1   36                      1  0.0  1.0
11       0   49                      2  1.0  0.0
12       1   68                      1  0.0  1.0
13       0   57                      2  1.0  0.0
14       1   40                      3  0.0  1.0
15       0   54                      3  1.0  0.0
16       1   44                      1  0.0  1.0
17       0   51                      2  1.0  0.0
18       1   48                      1  0.0  1.0
19       0   33                      3  1.0  0.0
20       1   70                      2  0.0  1.0
21       0   59                      1  1.0  0.0
22       1   44                      1  0.0  1.0
23       0   39                      3  1.0  0.0
24       1   50                      2  0.0  1.0
25       0   53                      1  1.0  0.0
26       1   64                      2  0.0  1.0
27       0   66                      1  1.0  0.0
28       1   60                      3  0.0  1.0
29       0   47                      1  1.0  0.0
30       1   58                      2  0.0  1.0